services:
  backend:
    image: backend
    container_name: backend_conatiner
    build: 
      context: ./backend
      dockerfile: dockerfile
      target: runner
    ports:
      - 8000:8000

  frontend:
    image: frontend
    container_name: frontend_container
    build: 
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 80:80